# model params
backbone:

image_size: 160
embedding_size: 512



# hyper params
optimizer: 'ADAM'    # ADADELTA, ADAGRAD, ADAM, ADAMAX, FTRL, NADAM, RMSPROP, SGD
learning_rate: 0.01

# DP params
dp_enabled: False
noise_multiplier: 1.3
l2_norm_clip: 1.5
num_microbatches: 256
target_delta: 0.001    # Generally set to less than inverse of population size

loss_type: 'logit'   # logit or triplet
logits_scale: 64.0
logits_margin1: 1.0   # m1: sphereface should >= 1
logits_margin2: 0.2   # m2: cosineface should >= 0
logits_margin3: 0.3   # m3: arcface    should >= 0

center_loss_factor: 0.0  # center loss
center_alpha: 0.9   # center update rate

alpha: 0.2     # triplet margin

# run params

batch_size: 16
epoch_num: 100

valid_num: 256          # half pos and half neg
valid_batch_size: 16
thresh: 0.2
below_fpr: 0.001        # fpr should below this
# paths

train_dir: '/ufrc/butler/w.garcia/dataset/Georgia_Tech_Faces/mtcnnpy_160_split/train'
valid_dir: '/ufrc/butler/w.garcia/dataset/Georgia_Tech_Faces/mtcnnpy_160_split/val'
test_dir: '/ufrc/butler/w.garcia/dataset/Georgia_Tech_Faces/mtcnnpy_160_split/test'
ckpt_dir: 'models/arcface_lr-0.01_emb-512'
summary_dir: 'logs/arcface_lr-0.01_emb-512'
